name: Node.js CI
on:
  pull_request:
    branches: ['master']

jobs:
  code-style:
    runs-on: ubuntu-latest
    name: code-style
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup deps
        uses: ./.github/actions/install-deps

      - name: Code style
        run: pnpm code-style
